### ISSUE TITLE
Storage Labs

### ISSUE THREAD

**Issue by irfanelahi-ds** [irfanelahi-ds/SEBC#3]

**Comment by irfanelahi-ds** [comment]
Link to Cloudera Manager instance:
http://ec2-52-65-127-89.ap-southeast-2.compute.amazonaws.com:7180/cmf/login

**Comment by irfanelahi-ds** [comment]
While running distcp, with HA enabled, it gave error that the cluster is in StandBy mode and thus read operation couldn't be performed. 
I disabled HA and then ran distcp again (with the command details shared) in PULL mode. However, it gave error that the source and destination cluster have different block size. I checked in the configuration and the block size is the same.

**Comment by mfernest** [comment]
This blocker would have been a good opportunity to read the logs and get to the root of the problem. Here again you've summarized a lot of work rather than show the results of execution, which make it difficult to understand what difficulties were at play.

The HA issue is a easy one to understand: the command you listed doesn't point to the logical nameservice property of an HA NameNode. Therefore you had a 50% chance of addressing the standby NameNode by giving a specific address.
